### PR TITLE
Option for lens definition in submodule 

### PR DESCRIPTION
**Pull request by didier-wenzek**
Here is my proposal for https://github.com/pdonadeo/ocaml-lens/issues/5.

I changed the option name to `submodule` (because using `module` leads to syntax errors).

### CODE REVIEW

**Comment by ghost** [comment]
@pdonadeo any progress on merging this?

**Comment by pdonadeo** [comment]
@orbifx sorry, I'm very busy these days. I plan to test, merge and release in a couple of days.

**Comment by pdonadeo** [comment]
There are two problems in the patch:

1. test does not compile: it's not critical but I'd like to release with compiling tests
2. the `String.capitalize_ascii` is used [here](https://github.com/didier-wenzek/ocaml-lens/blob/master/ppx_deriving/ppx_deriving_lens.ml#L74). This function is only available from OCaml 4.03.0, but I'd like to keep compatibility at least with 4.02.3. @didier-wenzek is it a problem for you if I replace `String.capitalize_ascii` with `String.capitalize`? I know it's deprecated but it's still present in 4.04.

In any case I want to release this week end, hopefully with tests. Meanwhile I'm going to merge.

**Comment by didier-wenzek** [comment]
This is not a problem to use String.capitalize. The best would be to use a function provided by ppx_deriving to make a module name from a string; but I failed to find such a function in the API.

**Comment by didier-wenzek** [comment]
For the test, I tried again to fix the build, but failed. I have never used oasis and I did not find the way to tell the dependency over the local lens.ppx_deriving module.

Currently, the build triggers the command
`ocamlfind ocamldep -package oUnit -package ppx_deriving -package ppx_deriving.api -package ppx_tools.metaquot -modules ppx_test/test_deriving_lens.ml > ppx_test/test_deriving_lens.ml.depends`

The missing dependency is `-ppxopt "ppx_deriving,./ppx_deriving/lens_ppx_deriving.cma"`

**Comment by ghost** [comment]
Looking forward to the release, as I wish to refactor [Logarion](https://github.com/orbifx/logarion/) using this feature.

**Pull request merged**
