### PR TITLE
Add a draft for a PPX-rewriter generating code for lenses

### PR DESCRIPTION
**Pull request by foretspaisibles**
This is still work in progress, there is two things to do:
- Integrate with the build system, unluckily I have no experience with oasis.
- Replace the Parsetree blobs with somethig easier to handle, probably using metaquot.

### CODE REVIEW

**Comment by rgrinberg** [comment]
What's the difference between this and #2

**Comment by foretspaisibles** [comment]
Ho, it is fantastic that it already exists!  I looked around for the generator and could not find it, and mistaken `avsm/ocaml-lens` for the main repository, this is why I overlooked #2. It looks like a good job!

**Comment by pdonadeo** [comment]
I'm finally in my week of vacation, so I'm considering #2 and #3 for merge. Keep in touch :-)

**Comment by pdonadeo** [comment]
@michipili I'm sorry but I decided to merge #2 which is more complete by far.

**Comment by foretspaisibles** [comment]
No need to be sorry #2 is much better than the minimal example I have put together in this PR. Thanks! :)

**Pull request closed without merging**
